version: '3.3'
services:
  gui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_gui
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
      - kafka4
      - kafka5
    environment:
      KAFKA_CLUSTERS_0_NAME: 'local1'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka1:29092'
      KAFKA_CLUSTERS_0_NAME: 'local2'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka2:29092'
      KAFKA_CLUSTERS_0_NAME: 'local3'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka3:29092'
      KAFKA_CLUSTERS_0_NAME: 'local4'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka4:29092'
      KAFKA_CLUSTERS_0_NAME: 'local5'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka5:29092'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    restart: on-failure
    ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
    - ZOOKEEPER_SERVER_ID=1
    - ZOOKEEPER_CLIENT_PORT=2181
    - ZOOKEEPER_TICK_TIME=2000

  kafka1:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka1
    restart: on-failure
    depends_on:
    - zookeeper
    ports:
    - "9091:9091"
    environment:
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9091,PLAINTEXT_INTERNAL://kafka1:29092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_BROKER_ID=1
    - BOOTSTRAP_SERVERS=kafka1:29092,kafka2:29092,kafka3:29092,kafka4:29092,kafka5:29092
    - ZOOKEEPER=zookeeper:2181
    - KAFKA_NUM_PARTITIONS=5
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=5
    - KAFKA_MIN_INSYNC_REPLICAS=3
    - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL

  kafka2:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka2
    restart: on-failure
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka2:29092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_BROKER_ID=2
    - BOOTSTRAP_SERVERS=kafka1:29092,kafka2:29092,kafka3:29092,kafka4:29092,kafka5:29092
    - ZOOKEEPER=zookeeper:2181
    - KAFKA_NUM_PARTITIONS=5
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=5
    - KAFKA_MIN_INSYNC_REPLICAS=3
    - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL

  kafka3:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka3
    restart: on-failure
    depends_on:
    - zookeeper
    ports:
    - "9093:9093"
    environment:
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093,PLAINTEXT_INTERNAL://kafka3:29092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_BROKER_ID=3
    - BOOTSTRAP_SERVERS=kafka1:29092,kafka2:29092,kafka3:29092,kafka4:29092,kafka5:29092
    - ZOOKEEPER=zookeeper:2181
    - KAFKA_NUM_PARTITIONS=5
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=5
    - KAFKA_MIN_INSYNC_REPLICAS=3
    - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL

  kafka4:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka4
    restart: on-failure
    depends_on:
    - zookeeper
    ports:
    - "9094:9094"
    environment:
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9094,PLAINTEXT_INTERNAL://kafka4:29092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_BROKER_ID=4
    - BOOTSTRAP_SERVERS=kafka1:29092,kafka2:29092,kafka3:29092,kafka4:29092,kafka5:29092
    - ZOOKEEPER=zookeeper:2181
    - KAFKA_NUM_PARTITIONS=5
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=5
    - KAFKA_MIN_INSYNC_REPLICAS=3
    - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL

  kafka5:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka5
    restart: on-failure
    depends_on:
    - zookeeper
    ports:
    - "9095:9095"
    environment:
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9095,PLAINTEXT_INTERNAL://kafka5:29092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_BROKER_ID=5
    - BOOTSTRAP_SERVERS=kafka1:29092,kafka2:29092,kafka3:29092,kafka4:29092,kafka5:29092
    - ZOOKEEPER=zookeeper:2181
    - KAFKA_NUM_PARTITIONS=5
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=5
    - KAFKA_MIN_INSYNC_REPLICAS=3
    - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL